# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["v1.x", canary]
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.version }}

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno task test
      - name: Create coverage report
        run: deno coverage --unstable ./coverage --lcov --exclude="test\.(ts|tsx|mts|js|mjs|jsx|cjs|cts)|exceptions\.ts|logger\.ts"  > coverage.lcov
      - name: Collect coverage
        uses: codecov/codecov-action@v1.0.10 # upload the report on Codecov
        with:
          file: ./coverage.lcov
